version: "3.4"
services:
  mcup:
    container_name: mcup
    hostname: mcup
    image: mcup
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    tty: true
    volumes:
      - ${PWD:-.}:/home/root/mcup
